// <auto-generated />
using System;
using DesafioSegfy.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesafioSegfy.Migrations
{
    [DbContext(typeof(SegfyDbContext))]
    partial class SegfyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DesafioSegfy.Domain.Entities.Apolice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataFimVigencia")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataIncioVigencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroApolice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorPremio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CpfCnpj")
                        .IsUnique();

                    b.HasIndex("NumeroApolice")
                        .IsUnique();

                    b.ToTable("Apolice", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
